services:
  fastapi:
    build: ./fastapi_app
    container_name: fastapi
    hostname: fastapi
    environment:
      - CAT_API_URL=https://api.thecatapi.com/v1/images/search
      - DOG_API_URL=https://api.thedogapi.com/v1/images/search
    networks:
      - app_net

  proxy:
    image: nginx:latest
    container_name: proxy
    hostname: proxy
    ports:
      - "8080:8080"   # Only proxy is exposed
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
