name: CI

on:
  push:                                           # run tests when you push to any branch
    branches: ["**"]
  pull_request:                                    # also run tests when you open a PR

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: .                                 # so `from app.main import app` works
                    
                    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Run Ruff (linting)
        run: ruff check .

      - name: Lint code with Ruff
        run: ruff check . --output-format=github --target-version=py312

      - name: Check code formatting with Ruff
        run: ruff format . --diff --target-version=py312
        continue-on-error: true

      - name: Run tests
        run: pytest -v
